// The browser results grid: machine x browser, the latest result of each
// pair from tests/browsers/usage.jsonl, with what's installed from
// inventory.json.
//
//   node tests/browsers/report.mjs            # print it (Markdown)
//   node tests/browsers/report.mjs --write    # replace the section in docs/test-results.md
import fs from 'node:fs';
import path from 'node:path';
import { MACHINES, BROWSERS as BROWSERS_L } from './compat.mjs';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const DOC = path.join(HERE, '..', '..', 'docs', 'test-results.md');
const START = '<!-- browsers:start (tests/browsers/report.mjs) -->';
const END = '<!-- browsers:end -->';

const ORDER = MACHINES.map((m) => m[0]);
const LABEL = Object.fromEntries(MACHINES.map((m) => [m[0], m[1]]));
const BLABEL = Object.fromEntries(BROWSERS_L);
const BROWSERS = BROWSERS_L.map((b) => b[0]);

const inv = JSON.parse(fs.readFileSync(path.join(HERE, 'inventory.json'), 'utf8'));
const usage = fs.existsSync(path.join(HERE, 'usage.jsonl'))
  ? fs.readFileSync(path.join(HERE, 'usage.jsonl'), 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l)) : [];

const latest = new Map(), runs = new Map();
for (const u of usage) {
  const k = u.machine + '/' + u.browser;
  runs.set(k, (runs.get(k) || 0) + 1);
  // An infrastructure error doesn't replace a real result.
  if (!/^error/.test(u.result) || !latest.has(k) || /^error/.test(latest.get(k).result)) latest.set(k, u);
}

const major = (v) => String(v || '').split('.')[0];
const cols = BROWSERS.filter((b) => Object.values(inv.machines).some((m) => (m.browsers || []).some((x) => x.id === b)));
const lines = [];
lines.push(`| Machine | ${cols.map((c) => BLABEL[c]).join(' | ')} |`, `| --- | ${cols.map(() => '---').join(' | ')} |`);
const notes = [];
let counts = { pass: 0, fail: 0, unsupported: 0, error: 0, untested: 0, none: 0 };
for (const name of ORDER.filter((n) => inv.machines[n])) {
  const m = inv.machines[name];
  const cells = cols.map((b) => {
    const e = (m.browsers || []).find((x) => x.id === b);
    if (!e) return '';
    if (!e.binary) { counts.none++; notes.push(`${LABEL[name]} ${BLABEL[b]}: can't run here: ${e.notes || ''}`); return 'can\'t run'; }
    const u = latest.get(name + '/' + b);
    const v = major(u && u.version || e.version);
    if (!u) { counts.untested++; return (e.driver ? 'untested ' : 'no driver ') + v; }
    const kind = u.result.split(':')[0];
    counts[kind] = (counts[kind] || 0) + 1;
    if (kind !== 'pass') notes.push(`${LABEL[name]} ${BLABEL[b]} ${u.version}: ${u.result}`);
    return { pass: `✓ ${v}`, fail: `✗ ${v}`, unsupported: `too old ${v}`, error: `error ${v}` }[kind] || kind;
  });
  lines.push(`| ${LABEL[name]} | ${cells.join(' | ')} |`);
}
const total = usage.length;
const out = [START, '',
  `Generated by \`tests/browsers/report.mjs\` from \`tests/browsers/usage.jsonl\` (${total} runs; the latest real result for each pair, `,
  'with the major version it ran). ✓ every check passed · ✗ a check failed · too old: the page\'s startup check found missing features ',
  '(it says so on screen) · error: the run couldn\'t be done (driver, SSH) · can\'t run: the browser doesn\'t start on that OS.', '',
  ...lines, '',
  `**${Object.entries(counts).filter(([, n]) => n).map(([k, n]) => `${n} ${k}`).join(', ')}.**`, '',
  ...(notes.length ? ['Not passing:', '', ...notes.map((n) => '- ' + n.replace(/\|/g, '\\|')), ''] : []),
  END].join('\n');

if (process.argv.includes('--write')) {
  let doc = fs.readFileSync(DOC, 'utf8');
  if (doc.includes(START)) doc = doc.slice(0, doc.indexOf(START)) + out + doc.slice(doc.indexOf(END) + END.length);
  else doc = doc.replace(/\s*$/, '\n\n## Browsers (the one-file page)\n\n' + out + '\n');
  fs.writeFileSync(DOC, doc);
  console.log('wrote ' + DOC);
} else console.log(out);
