#!/usr/bin/env python3
"""Write docs/test-results.md's main grid from results.jsonl (latest per cell).

usage: report.py [RESULTS ...]

Every column says which architecture that machine is (tests/arch/machines.py),
so a green row can no longer mean "on amd64 only", and a cell that the
resolver makes no plan block for reads differently from one the catalogue
says has no release.
"""
import collections
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "arch"))
import machines                                            # noqa: E402

files = sys.argv[1:] or [str(HERE / "results.jsonl")]
rows = [json.loads(l) for f in files for l in open(f) if l.strip()]
last = {}
# The newest run of each cell wins, by the run's own `time` and not by the
# order the files happen to be given in: a results file named with a suffix
# ("2026-09-20-macos-base.jsonl") is easy to pass before the plain one for
# the same day, and the later run would then be thrown away.
for r in rows:
    key = (r["target"], r["runtime"], r["mode"])
    was = last.get(key)
    if was is not None and str(was.get("time", "")) > str(r.get("time", "")):
        continue
    last[key] = r
ORDER = ["xp", "vista", "7", "8.1", "10", "11", "2022", "10x86", "ltsc2021", "ltsc2024", "11de", "2025core",
         "centos6", "centos7", "ubuntu1404", "ubuntu1604", "ubuntu1804", "rocky8", "ubuntu2004", "ubuntu2204",
         "debian12", "linux", "alpine", "debian12x86", "debian12-i386", "debian12-i386-libs", "alpine324-i386", "mac"]
RTS = ["python", "python2", "node", "ruby", "php", "java", "dotnet", "r", "go", "rust", "zig", "nim", "cc"]
targets = [t for t in ORDER if any(k[0] == t for k in last)]
targets += [t for t in sorted({k[0] for k in last}) if t not in ORDER]


def head(t):
    m = machines.MACHINES.get(t)
    if not m:
        return t + " (?)"
    bits = machines.SHORT.get(m["arch"], m["arch"])
    return f"{m['label']} · {bits}"


def cell(t, rt):
    """One machine x runtime cell, over the modes that were run."""
    rs = [r for r in (last.get((t, rt, m)) for m in "ABC") if r]
    if not rs:
        return " "
    res = {r["result"] for r in rs}
    if res == {"pass"}:
        return "✓"
    if "fail" in res:
        return "✗"
    # A failure we already know about and have written down (today: macOS
    # installers killed by Gatekeeper, until there is a Developer ID). It
    # is shown apart from ✗ so a new macOS failure is still visible.
    if res <= {"known", "pass"}:
        return "!"
    if res <= {"n/a", "no-plan"}:
        if any(r["detail"].startswith("refused") for r in rs):
            return "refused"
        if any("needs root" in r["detail"] for r in rs):
            return "root"
        return "∅" if "no-plan" in res else "–"
    return "part"


out = ["# Test results", "",
       "Generated by `tests/matrix/report.py` from `tests/matrix/results/` (the latest result for each",
       "cell). Each cell is one runtime's hello world, built through the live API in modes A, B and C,",
       "installed unattended, run through its launcher (it must print `hello from <runtime>`), then",
       "uninstalled with a check that nothing is left (docs/plan.md section 3).", "",
       "Each column says the machine's architecture: **64** amd64 · **32** 32-bit x86 · **a64** arm64.",
       "Every cell also checks it: the architecture the installer's own engine detected, and the ELF",
       "class of the runtime it installed, must both be that machine's, or the cell fails.", "",
       "✓ passes in all three modes · ✗ fails in at least one · ! fails only in a way we already know",
       "about and have written down (listed at the end, with what would clear it) · – no release in the catalogue runs on",
       "that OS and architecture (the installer says so) · ∅ the plan has no block for that machine at",
       "all, so the cell is **untested**, not n/a · root: needs a system package, and the unattended",
       "installer stops with the exact command to run · refused: a combination the catalogue knows",
       "cannot work, so the installer stops up front and says why · blank: not run", "",
       "| Runtime | " + " | ".join(head(t) for t in targets) + " |",
       "| --- | " + " | ".join("---" for _ in targets) + " |"]
for rt in RTS:
    if not any(k[1] == rt for k in last):
        continue
    out.append(f"| {rt} | " + " | ".join(cell(t, rt) for t in targets) + " |")
# Count what the grid draws. The rows above skip a runtime that is not in
# RTS, so counting every result made the total larger than the table it
# sits under -- the extra cells were behaviour rows the grid never draws,
# and the difference read as coverage nobody could point at.
drawn = {k: r for k, r in last.items() if k[1] in RTS}
tot = collections.Counter(r["result"] for r in drawn.values())
out += ["", f"**{len(drawn)} cells: {tot['pass']} pass, {tot['n/a']} n/a, {tot['no-plan']} no plan block, "
        f"{tot['known']} known failure, {tot['fail']} fail.**"
        + (f" ({len(last) - len(drawn)} more results are not runtime cells and are not drawn above.)"
           if len(last) != len(drawn) else ""), ""]

unwitnessed = sum(1 for r in drawn.values() if r.get("arch_unwitnessed"))
if unwitnessed:
    out += [f"{unwitnessed} of those cells are missing at least one architecture witness "
            "(`arch_unwitnessed` names which), so their architecture comparisons did not run.", ""]

by_arch = collections.Counter((r.get("arch") or machines.arch_of(r["target"]), r["result"]) for r in drawn.values())
arches = sorted({a for a, _ in by_arch})
out += ["By architecture:", "",
        "| Architecture | cells | pass | n/a | no plan block | known | fail |",
        "| --- | --- | --- | --- | --- | --- | --- |"]
for a in arches:
    n = sum(v for (aa, _), v in by_arch.items() if aa == a)
    out.append(f"| {a} | {n} | " + " | ".join(str(by_arch.get((a, k), 0))
                                              for k in ("pass", "n/a", "no-plan", "known", "fail")) + " |")

out += ["", "## Every failure", "",
        "Known failures (`!`) are listed after these: they are expected, written down, and say what",
        "would clear them. Everything here is unexpected.", "",
        "| OS | Arch | Runtime | Mode | Detail |", "| --- | --- | --- | --- | --- |"]
order = {t: i for i, t in enumerate(targets)}
for (t, rt, m), r in sorted(last.items(), key=lambda kv: (order.get(kv[0][0], 99), kv[0][1], kv[0][2])):
    if r["result"] == "fail":
        d = " ".join(r["detail"].split())[:160].replace("|", "/")
        out.append(f"| {machines.label_of(t, False)} | {r.get('arch') or machines.arch_of(r['target'])} | {rt} | {m} | {d} |")

known = [(k, r) for k, r in sorted(last.items(), key=lambda kv: (order.get(kv[0][0], 99), kv[0][1], kv[0][2]))
         if r["result"] == "known"]
if known:
    out += ["", "## Known failures", "",
            "Expected, and shown as `!` rather than `✗` so a new failure on the same platform is not",
            "lost among them.", "",
            "| OS | Arch | Runtime | Mode | Detail |", "| --- | --- | --- | --- | --- |"]
    for (t, rt, m), r in known:
        d = " ".join(r["detail"].split())[:200].replace("|", "/")
        out.append(f"| {machines.label_of(t, False)} | {r.get('arch') or machines.arch_of(r['target'])} | {rt} | {m} | {d} |")
print("\n".join(out))
