#!/usr/bin/env python3
"""Write docs/test-results.md from results.jsonl (latest result per cell)."""
import collections, json, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
rows = [json.loads(l) for l in open(sys.argv[1] if len(sys.argv) > 1 else HERE / "results.jsonl")]
last = {}
for r in rows:
    last[(r["target"], r["runtime"], r["mode"])] = r
ORDER = ["xp", "vista", "7", "8.1", "10", "11", "2022", "10x86", "ltsc2021", "11de", "2025core", "centos6", "centos7", "ubuntu1404", "ubuntu1604",
         "ubuntu1804", "rocky8", "ubuntu2004", "ubuntu2204", "debian12", "linux", "alpine", "mac"]
NAMES = {"xp": "XP", "vista": "Vista", "7": "Win 7", "8.1": "Win 8.1", "10": "Win 10", "11": "Win 11",
         "2022": "Srv 2022", "10x86": "Win 10 x86", "ltsc2021": "LTSC 2021", "11de": "Win 11 DE (Jörg)",
         "2025core": "Srv 2025 Core", "centos6": "CentOS 6", "centos7": "CentOS 7", "ubuntu1404": "Ubuntu 14.04",
         "ubuntu1604": "Ubuntu 16.04", "ubuntu1804": "Ubuntu 18.04", "rocky8": "Rocky 8",
         "ubuntu2004": "Ubuntu 20.04", "ubuntu2204": "Ubuntu 22.04", "debian12": "Debian 12",
         "linux": "Ubuntu 24.04", "alpine": "Alpine", "mac": "macOS 26"}
RTS = ["python", "node", "ruby", "php", "java", "dotnet", "r", "go", "rust", "zig", "nim", "cc"]
targets = [t for t in ORDER if any(k[0] == t for k in last)]


def cell(t, rt):
    rs = [last.get((t, rt, m)) for m in "ABC"]
    if not any(rs):
        return " "
    res = {r["result"] for r in rs if r}
    if res == {"pass"}:
        return "✓"
    if "fail" in res:
        return "✗"
    if all(r and r["result"] == "n/a" for r in rs):
        return "root" if any("needs root" in r["detail"] for r in rs) else "–"
    return "part"


out = ["# Test results", "",
       "Generated by `tests/matrix/report.py` from `tests/matrix/results/` (the latest result for each",
       "cell). Each cell is one runtime's hello world, built through the live API in modes A, B and C,",
       "installed unattended, run through its launcher (it must print `hello from <runtime>`), then",
       "uninstalled with a check that nothing is left (docs/plan.md section 3).", "",
       "✓ passes in all three modes · ✗ fails in at least one · – no release in the catalogue runs on",
       "that OS (the installer says so) · root: needs a system package, and the unattended installer",
       "stops with the exact command to run", "",
       "| Runtime | " + " | ".join(NAMES[t] for t in targets) + " |",
       "| --- | " + " | ".join("---" for _ in targets) + " |"]
for rt in RTS:
    out.append(f"| {rt} | " + " | ".join(cell(t, rt) for t in targets) + " |")
tot = collections.Counter(r["result"] for r in last.values())
out += ["", f"**{len(last)} cells: {tot['pass']} pass, {tot['n/a']} n/a, {tot['fail']} fail.**", "",
        "## Every failure", "", "| OS | Runtime | Mode | Detail |", "| --- | --- | --- | --- |"]
for (t, rt, m), r in sorted(last.items(), key=lambda kv: (ORDER.index(kv[0][0]), kv[0][1], kv[0][2])):
    if r["result"] == "fail":
        d = " ".join(r["detail"].split())[:160].replace("|", "/")
        out.append(f"| {NAMES[t]} | {rt} | {m} | {d} |")
print("\n".join(out))
