#!/usr/bin/env python3
"""Write catalog/GAPS-TO-REVIEW.md: everything that couldn't be found or downloaded.

Sources: each runtime's gaps.json (never found) and catalog/download-gaps.json
(found but failed to download or verify). Known explanations for specific
download failures live in KNOWN below; unexplained failures are listed as such.
"""
import json
from collections import Counter, defaultdict
from pathlib import Path

CATALOG = Path(__file__).resolve().parents[1]
FOLDERS = ["python", "node", "java", "dotnet", "go", "rust", "php", "r", "ruby", "nim", "zig", "cc"]

# (runtime, version, os, variant-or-None) -> explanation, found by investigating the failure.
KNOWN = {
    ("dotnet", "7.0.20", "macos", "runtime"):
        "Microsoft serves a file of the listed size whose SHA-512 differs from the hash in its own "
        "release metadata (checked on both builds.dotnet.microsoft.com and dotnetcli.blob.core.windows.net). "
        "Also reported publicly (MacPorts issue #68580). The earliest Wayback capture (2025-07-09) already "
        "has the same mismatched bytes, so no archived original exists. Not accepted.",
    ("php", "*", "*", "static-php-cli"):
        "Size differs from the size recorded during scraping. Likely cause (not confirmed): static-php-cli "
        "community builds are rebuilt in place under the same file name. No vendor checksum exists. Re-scrape and download "
        "together to capture a consistent build.",
    ("r", "1.8.1", "windows", None):
        "CRAN's published md5 is wrong: the live rw1081.exe and its oldest Wayback capture are byte-identical "
        "and neither matches CRAN's md5sum listing. Not a download or mirror problem.",
}


def explain(r):
    for key in ((r["runtime"], r["version"], r["os"], r.get("variant")),
                (r["runtime"], "*", "*", r.get("variant"))):
        if key in KNOWN:
            return KNOWN[key]
    return None


def main():
    out = ["# Gaps to review", "",
           "Generated by `catalog/tools/gaps_report.py`. Two kinds of gap:", "",
           "1. **Not found:** a runtime version that plausibly existed for an OS/architecture, but no "
           "downloadable file could be located (each runtime's `gaps.json`).",
           "2. **Download failed:** a file was catalogued but couldn't be downloaded, or didn't match its "
           "recorded checksum or size (`download-gaps.json`). Failed files were deleted, never kept.", ""]

    out += ["## Summary", "", "| Runtime | Not found | Download failed or skipped |", "| --- | --- | --- |"]
    dl = json.loads((CATALOG / "download-gaps.json").read_text()) if (CATALOG / "download-gaps.json").exists() else {}
    per = {}
    for f in FOLDERS:
        gaps = json.loads((CATALOG / f / "gaps.json").read_text()) if (CATALOG / f / "gaps.json").exists() else []
        per[f] = gaps
        failed = [r for key, items in dl.items() for r in items if (key == f)]
        out.append(f"| {f} | {len(gaps)} | {len(failed)} |")

    out += ["", "## Download failures", ""]
    any_fail = False
    for key, items in dl.items():
        for r in items:
            any_fail = True
            why = explain(r) or "Unexplained, needs investigation."
            last = (r.get("errors") or [r.get("reason", "")])[-1]
            out.append(f"- **{r['runtime']} {r['version']}** {r['os']}/{r['arch']}"
                       f"{' ' + r['variant'] if r.get('variant') else ''}: {r['status']}. {why}  \n"
                       f"  Last error: `{last[:200]}`")
    if not any_fail:
        out.append("None.")

    out += ["", "## Not found, by runtime", ""]
    for f in FOLDERS:
        gaps = per[f]
        if not gaps:
            continue
        out += [f"### {f} ({len(gaps)})", ""]
        reasons = defaultdict(list)
        for g in gaps:
            reasons[g["reason"]].append(g)
        for reason, gs in sorted(reasons.items(), key=lambda kv: -len(kv[1])):
            combos = ", ".join(sorted({f"{g['major']} {g['os']}/{g['arch']}" for g in gs})[:12])
            more = f" … (+{len(gs) - 12})" if len(gs) > 12 else ""
            out.append(f"- {reason}  \n  Affects: {combos}{more}")
        out.append("")

    out += ["## Data quality notes to review", "",
            "- **Python 3.8 Windows OS support** in `python/limitations.json` says Vista and later. "
            "The operator's tested builds use 3.7.0 for Vista, and 3.8 may not support Vista officially. Check.",
            "- **python.org's API** records the checksum and size of the *decompressed* tarball for old `.tgz` "
            "source files; handled by `python/fix_tgz_checksums.py` and `applies_to: decompressed`.",
            "- **Checksum coverage is weak** for older LLVM (pre-2025 GitHub assets and releases.llvm.org), GCC "
            "source, MSVC redistributables, most archived PHP Windows builds, and R on macOS/Linux. Those "
            "downloads are verified by size only.",
            "- **Limitation confidence** is mostly low for C/C++ toolchains and R 1.x/2.x; see each "
            "`limitations.json` `confidence` field.", ""]
    (CATALOG / "GAPS-TO-REVIEW.md").write_text("\n".join(out))
    print(f"wrote {CATALOG / 'GAPS-TO-REVIEW.md'}")


if __name__ == "__main__":
    main()
