#!/usr/bin/env python3
"""Turn the two ESM bundles in vendor/ (resedit-js and its pe-library
dependency, both MIT, (c) 2018 jet) into one classic script,
vendor/resedit-bundle.js, that sets globalThis.__IB_RESEDIT to the resedit
module namespace.

The site pages load it with <script src>, and tools/make_standalone.py inlines
its text into the self-contained editor page, so icon editing needs no network.

    python3 tools/build_resedit_bundle.py

The +esm bundles are fetched once with:
    curl https://cdn.jsdelivr.net/npm/resedit@2.0.3/+esm     -o vendor/resedit-2.0.3.esm.js
    curl https://cdn.jsdelivr.net/npm/pe-library@1.0.1/+esm  -o vendor/pe-library-1.0.1.esm.js
    curl https://cdn.jsdelivr.net/npm/resedit@2.0.3/LICENSE    -o vendor/LICENSE.resedit
    curl https://cdn.jsdelivr.net/npm/pe-library@1.0.1/LICENSE -o vendor/LICENSE.pe-library
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PELIB = "vendor/pe-library-1.0.1.esm.js"
RESEDIT = "vendor/resedit-2.0.3.esm.js"
OUT = "vendor/resedit-bundle.js"

EXPORT_RE = re.compile(r"export\{([^}]*)\}\s*;?")
SOURCEMAP_RE = re.compile(r"^//# sourceMappingURL=.*$", re.M)
# import{A as B,...}from"/npm/pe-library@1.0.1/+esm"
IMPORT_RE = re.compile(r'import\{([^}]*)\}from"[^"]*pe-library[^"]*"\s*;?')


def read(rel):
    with open(os.path.join(ROOT, rel)) as f:
        return SOURCEMAP_RE.sub("", f.read()).rstrip()


def parse_map(spec):
    """'a as B,c as D' -> [(a,B),(c,D)]; bare 'a' -> [(a,a)]."""
    out = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        m = re.match(r"(\S+)\s+as\s+(\S+)$", part)
        out.append((m.group(1), m.group(2)) if m else (part, part))
    return out


def strip_export(src, what):
    m = EXPORT_RE.search(src)
    if not m:
        sys.exit(f"{what}: no trailing export{{...}} found")
    pairs = parse_map(m.group(1))
    body = src[: m.start()].rstrip()
    obj = "{" + ",".join(f"{name}:{internal}" for internal, name in pairs) + "}"
    return body, obj


def main():
    pelib = read(PELIB)
    if "import" in pelib.split("\n", 1)[0] and "pe-library" in pelib:
        pass
    # pe-library has no imports of its own; just strip its export.
    pelib_body, pelib_obj = strip_export(pelib, PELIB)

    resedit = read(RESEDIT)
    # Rewire pe-library imports to the local IIFE result.
    def repl(m):
        pairs = parse_map(m.group(1))
        return "const {" + ",".join(f"{orig}:{alias}" for orig, alias in pairs) + "}=__ib_pelib;"
    resedit, n = IMPORT_RE.subn(repl, resedit)
    if n == 0:
        sys.exit("resedit: no pe-library import found to rewire")
    resedit_body, resedit_obj = strip_export(resedit, RESEDIT)

    for name, src in (("pe-library", pelib_body), ("resedit", resedit_body)):
        if re.search(r"(^|[^.\w])(?:import|export)\s*[\{\*]", src) or re.search(r'\bfrom"', src):
            sys.exit(f"{name}: a leftover import/export this script can't flatten")

    header = (
        "// resedit-js 2.0.3 and pe-library 1.0.1, bundled for Installer Builder.\n"
        "// Both are MIT licensed, Copyright (c) 2018 jet. Full licence text is in\n"
        "// vendor/LICENSE.resedit and vendor/LICENSE.pe-library. Generated by\n"
        "// tools/build_resedit_bundle.py from the packages' jsdelivr +esm builds;\n"
        "// do not edit by hand. Sets globalThis.__IB_RESEDIT to resedit's exports.\n"
    )
    out = (
        header
        + '"use strict";\n'
        + "var __ib_pelib=(function(){\n" + pelib_body + "\nreturn " + pelib_obj + ";\n})();\n"
        + "globalThis.__IB_RESEDIT=(function(){\n" + resedit_body + "\nreturn " + resedit_obj + ";\n})();\n"
    )
    path = os.path.join(ROOT, OUT)
    with open(path, "w") as f:
        f.write(out)
    print(f"wrote {OUT} ({len(out.encode()):,} bytes)")


if __name__ == "__main__":
    main()
